crm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", login_required(TemplateView.as_view(template_name="index.html")), name="index"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("login/submit", views.submit_login, name="submit_login"),
    path("customer/", include("customer.urls"))
]

customer/urls.py
from django.urls import path
from .views import CustomerListView, CustomerCreateView, CustomerUpdateView, CustomerDeleteView

app_name = "customer"

urlpatterns = [
    path("list/", CustomerListView.as_view(), name="customer-list"),
    path("", CustomerCreateView.as_view(), name="customer-create"),
    path("<int:id>/", CustomerUpdateView.as_view(), name="customer-update"),
    path("<int:id>/delete/", CustomerDeleteView.as_view(), name="customer-delete"),

]

core/models.py
from django.db import models

# Create your models here.

customer/models.py
from django.db import models
from django.urls import reverse


class Customer(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    birth_date = models.DateField()
    area_code = models.CharField(max_length=3)
    phone_number = models.CharField(max_length=9)
    country = models.CharField(max_length=30)
    state = models.CharField(max_length=30)
    city = models.CharField(max_length=30)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)


    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def get_full_phone_number(self):
        return F"({self.area_code}) {self.phone_number}"

    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"

    def get_full_city(self):
        return f"{self.city} - {self.state}"

    def get_absolute_url(self):
        return reverse("customer:customer-update", kwargs={"id": self.id})

    def get_delete_url(self):
        return reverse("customer:customer-delete", kwargs={"id": self.id})


class Meta:
    db_table = "customer"

customer/forms.py
from django import forms

from .models import Customer


class DateInput(forms.DateInput):
    input_type = "date"


class CustomerForm(forms.ModelForm):
    first_name = forms.CharField(label="Nome", error_messages={
                                 "max_length": "Nome não pode ter mais do que 30 caracteres"})
    last_name = forms.CharField(label="Sobrenome", error_messages={
                                 "max_length": "Sobrenome não pode ter mais do que 30 caracteres"})
    email = forms.EmailField(label="E-mail")
    birth_date = forms.DateField(
        label="Data de Nascimento", widget=DateInput())
    area_code = forms.RegexField(
        label="DDD", regex=r"\+?1?[0-9]{2}$", error_messages={"invalid": "Número de DDD inválido"})
    phone_number = forms.RegexField(
        label="Telefone", regex=r"\+?1?[0-9]{9,15}$", error_messages={"invalid": "Número de telefone inválido"})
    country = forms.CharField(label="País")
    state = forms.CharField(label="Estado")
    city = forms.CharField(label="Cidade")

    class Meta:
        model = Customer
        fields = (
            "first_name",
            "last_name",
            "email",
            "birth_date",
            "area_code",
            "phone_number",
            "country",
            "state",
            "city"
        )

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login as app_login, logout as app_logout
from django.contrib import messages
# Create your views here.


def login(request):
    return render(request, "login.html")


def submit_login(request):
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            app_login(request, user)
            return redirect("index")
        else:
            messages.error(
                request, "Usuário/Senha inválido. Por favor tente novamente")
    return redirect("login")


def logout(request):
    app_logout(request)
    return redirect("login")

customer/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import Customer
from .forms import CustomerForm
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.db.models import Q


class CustomerListView(ListView):
    template_name = "customer/customer_list.html"
    paginate_by = 5
    model = Customer

    def get_queryset(self):
        name = self.request.GET.get("name")
        if name:
            object_list = self.model.objects.filter(
                Q(first_name__icontains=name) | Q(last_name__icontains=name))
        else:
            object_list = self.model.objects.all()
        return object_list


class CustomerCreateView(CreateView):
    template_name = "customer/customer.html"
    form_class = CustomerForm

    def form_valid(self, form):
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("customer:customer-list")


class CustomerUpdateView(UpdateView):
    template_name = "customer/customer.html"
    form_class = CustomerForm

    def get_object(self):
        id = self.kwargs.get("id")
        return get_object_or_404(Customer, id=id)

    def form_valid(self, form):
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("customer:customer-list")


class CustomerDeleteView(DeleteView):
    def get_object(self):
        id = self.kwargs.get("id")
        return get_object_or_404(Customer, id=id)

    def get_success_url(self):
        return reverse("customer:customer-list")

core/templates/index.html
{% extends "model-page.html" %}

{% block content %}
   <div class="container">
      <div class="row">
        <div class="col-9"><h1>CRM</h1></div>
        <div class="col-6"><h2>Sistema de Gestão de Clientes</h2></div>
        <div class="col-6"><img src="https://i.imgur.com/6eft5SGh.jpg" class="img-fluid" alt="Responsive image" /></div>
      </div>
    </div>
{% endblock %}

core/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">

</head>

<body class="d-flex flex-column">
    <div class="sidenav">
        <div class="login-main-text">
            <h2>CRM<br>Sistema de Gestão de Clientes</h2>
        </div>
    </div>
    <div class="main">
        <div class="col-md-6 col-sm-12">
            <div class="login-form">
                <form action="submit" , method="POST">{% csrf_token %}
                    <div class="form-group">
                        <label>Usuário</label>
                        <input type="text" class="form-control" placeholder="Usuário" name="username">
                    </div>
                    <div class="form-group">
                        <label>Senha</label>
                        <input type="password" class="form-control" placeholder="Senha" name="password">
                    </div>
                    {% if messages %}
                    {% for message in messages %}
                    <div class="alert alert-danger">{{ message }}</div>
                    {% endfor %}

                    {% endif %}
                    <button type="submit" class="btn btn-black">Login</button>

                </form>
            </div>
        </div>
    </div>
</body>

</html>

core/templates/model-footer.html
<div class="container text-center">
    <small>Desenvolvido por Marcos Antonio</small>
</div>

core/templates/model-header.html
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <a class="navbar-brand" href={% url 'index' %}>CRM</a>
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'customer:customer-list' %}">Clientes</a>
        </li>
    </ul>
    <a class="" href="{% url 'logout' %}">Sair</a>
</nav>

core/templates/model-page.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
</head>

<body class="d-flex flex-column">
    <header>
        {% include "model-header.html" %}
    </header>
    <main class="content" style="margin-top: 5%;">
        <div class="container">
            {% block content %} {% endblock %}
        </div>
       
    </main>

    <footer class="py-4 bg-dark text-white-50">
        {% include "model-footer.html" %}
    </footer>

</body>

<style>
    html,
    body {
        height: 100%;
    }

    main {
        flex: 1 0 auto;
    }

    footer {
        flex-shrink: none;
        margin-top: 2em;
    }
</style>


</html>

customer/templates/customer/customer.html
{% extends "model-page.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <h2>Clientes</h2>
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
    {% endif %}
    
    <form method="POST">{% csrf_token %}
        {{ form |crispy }}
            <button type="submit" class="btn btn-primary">Salvar</button>
    </form>
    

{% endblock %}

customer/templates/customer/customer_list.html
{% extends "model-page.html" %}

{% block content %}
<h2>Clientes</h2>

<a href="{% url 'customer:customer-create' %}">
    <button type="button" class="btn btn-success" style="float: right; margin-bottom: 5px;">Adicionar</button>
</a>

<form>
    <div class="form-group mb-1">
        <input class="form-control" type="text" name="name" placeholder="Buscar por nome...">
    </div>    
    <button type="submit" class="btn btn-primary">Buscar</button>
</form>

<table class="table table-bordered mt-4">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Cidade</th>
            <th>Telefone</th>
            <th>Email</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for customer in customer_list%}
        <tr>
            <td><a href="{{ customer.get_absolute_url }}">{{customer.get_full_name }}</a></td>
            <td>{{ customer.get_full_city}}</td>
            <td>{{ customer.get_full_phone_number }}</td>
            <td>{{ customer.email }}</td>
            <form method="POST" action="{{ customer.get_delete_url }}">{% csrf_token %}
                <td><button type="submit" class="btn btn-danger">Excluir</button></td>
            </form>
        </tr>
        {% endfor %}

    </tbody>
</table>

<ul class="pagination">
    {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?{{ page_obj.previous_page_number }}">Anterior</a></li>
    {% else %}
        <li class="page-item disabled"><a class="page-link" href="#">Anterior</a></li>
    {% endif %}

    {% for object in page_obj.paginator.page_range%}
        <li class="page-item"><a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
    {% endfor %}

    {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?{{ page_obj.next_page_number }}">Próximo</a></li>
    {% else %}
        <li class="page-item disabled"><a class="page-link" href="#">Próximo</a></li>
    {% endif %}

</ul>

{% endblock %}